# fly.toml app configuration file generated for withered-surf-967 on 2023-05-16T15:22:25+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "withered-surf-967"
primary_region = "hkg"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
